### PR TITLE
Add Hungarian translation

### PR DESCRIPTION
**Pull request by gidano**

### CODE REVIEW

**Comment by gidano** [comment]
Thx!

GustavLindberg99 ***@***.***> ezt írta (időpont: 2023. okt.
13., Pén 12:28):

**Comment by GustavLindberg99** [comment]
Could you please update the Hungarian translation for the new version? The attached file contains the new strings that need to be translated.

[androiddrive_hu.zip](https://github.com/GustavLindberg99/AndroidDrive/files/13766320/androiddrive_hu.zip)

**Comment by gidano** [comment]
Please, here you go!
[androiddrive_hu_full.zip](https://github.com/GustavLindberg99/AndroidDrive/files/13766484/androiddrive_hu_full.zip)

**Comment by GustavLindberg99** [comment]
Could you please update the Hungarian translation for the new version? The attached file contains the new strings that need to be translated.

[androiddrive_hu.zip](https://github.com/user-attachments/files/17083918/androiddrive_hu.zip)

**Comment by GustavLindberg99** [comment]
Could you please update the Hungarian translation for the new version? The attached file contains the new strings that need to be translated.

[androiddrive_hu.zip](https://github.com/user-attachments/files/18227478/androiddrive_hu.zip)

**Comment by GustavLindberg99** [comment]
Thank you, but it doesn't seem like the file got attached. It says you replied via email, I suspect email attachments don't work when replying to pull requests, so you probably need to attach the file in GitHub directly.

**Comment by gidano** [comment]
Ok, I attach it here!
[androiddrive_hu.zip](https://github.com/user-attachments/files/18237234/androiddrive_hu.zip)

**Comment by GustavLindberg99** [comment]
Thank you, it worked.

**Comment by GustavLindberg99** [comment]
Could you please update the Hungarian translation for the new version? The attached file contains the new strings that need to be translated.

[androiddrive_hu.zip](https://github.com/user-attachments/files/19038447/androiddrive_hu.zip)

**Comment by GustavLindberg99** [comment]
Could you please update the Hungarian translation for the new version? The attached file contains the new strings that need to be translated.

[androiddrive_hu.zip](https://github.com/user-attachments/files/20273875/androiddrive_hu.zip)

**Pull request merged**
