### PR TITLE
Installer changes for multilanguage installer

### PR DESCRIPTION
**Pull request by bovirus**
@GustavLindberg99 

** Changes
- Use external iss file (androiddrive-setup-languages.iss) for languages and custom messages and avoid to modify main script for language changes Enable english/french/Italian version
- Setup file version
- Setup copyright info (and get current year)
- Setup modern interface
- Setup language dialog
- Get app version from exe file.

Please check and apply.

### CODE REVIEW

**Comment by GustavLindberg99** [comment]
Thanks. I fixed a few bugs in the main script. Since AndroidDrive is not yet available in other languages than English, I commented out the other languages for now to avoid giving the impression that AndroidDrive itself will be in the same language as the installer. I will change that back when I release a new version where the other languages will be available.

**Comment by bovirus** [comment]
@GustavLindberg99

Thanks.
I used multiple languages just to test multilanguage installer.
Could you please create a new installer to check it?

**Comment by GustavLindberg99** [comment]
I tested it and it worked fine. I just didn't include them in the actual installer so that people don't get confused when the installer is in their language but not the actual program.

**Comment by bovirus** [comment]
I believe that you just modify 'androiddrive-setup-languages.iss" leaving only english.

Did you test that in Windows program list icon is now ok?

**Comment by GustavLindberg99** [comment]
I accepted your pull request which means that all your changes have been applied. I also made some change myself afterwards, which is why your changes don't show up as the most recent.

I tested everything and it works as it should. Here are some screenshots:

Skärmbild 2023-10-02 213805'

Skärmbild 2023-10-02 214222

These screenshots are from the same version of the installer that I have uploaded and that is now online, so everything should work (except the languages, but I will fix that when I have time).

**Comment by GustavLindberg99** [comment]
Could you please update the Italian translation for the new version? The attached file contains the new strings that need to be translated.

[androiddrive_it.zip](https://github.com/GustavLindberg99/AndroidDrive/files/13766325/androiddrive_it.zip)

**Comment by bovirus** [comment]
@GustavLindberg99 

I attache dthe new language file

Question: multi period string like these

Device %1 is offline. Try unlocking the device, then unplugging it and re-plugging it.
ADB failed to start. Either the adb.exe file is missing, or you may have insufficient permissions to invoke the program.
An update is available. Do you want to install it now?
Dokan doesn't seem to be installed. Would you like to install it now?
ADB failed to start. Either the adb.exe file is missing, or you may have insufficient permissions to invoke the program.

How can ad a nelline here?

Device %1 is offline.</br>Try unlocking the device, then unplugging it and re-plugging it.
ADB failed to start.</br>Either the adb.exe file is missing, or you may have insufficient permissions to invoke the program.
An update is available.</br>Do you want to install it now?
Dokan doesn't seem to be installed.</br>Would you like to install it now?
ADB failed to start.</br>Either the adb.exe file is missing, or you may have insufficient permissions to invoke the program.

Please remind to separate always in english multiperiod with a new line.

Thanks.

**Comment by GustavLindberg99** [comment]
Could you please update the Italian translation for the new version? The attached file contains the new strings that need to be translated.

[androiddrive_it.zip](https://github.com/user-attachments/files/17083920/androiddrive_it.zip)

**Comment by bovirus** [comment]
@GustavLindberg99 

Done

[androiddrive_it.zip](https://github.com/user-attachments/files/17084455/androiddrive_it.zip)

Note: in .ts file there is an obsolete (vanish) string.

Please check if you can when you compile prpject language files to remove obsolete (vanish) strings.

If you use "lupdate" please add as command line "-no-obsolete"

Thanks.

**Comment by GustavLindberg99** [comment]
Could you please update the Italian translation for the new version? The attached file contains the new strings that need to be translated.

[androiddrive_it.zip](https://github.com/user-attachments/files/18227474/androiddrive_it.zip)

**Comment by bovirus** [comment]
@GustavLindberg99 

[androiddrive_it.zip](https://github.com/user-attachments/files/18227718/androiddrive_it.zip)

Thanks. Done.

**Comment by GustavLindberg99** [comment]
Could you please update the Italian translation for the new version? The attached file contains the new strings that need to be translated.

[androiddrive_it.zip](https://github.com/user-attachments/files/19038448/androiddrive_it.zip)

**Comment by bovirus** [comment]
@GustavLindberg99 

Thanks. Done.

[androiddrive_it.zip](https://github.com/user-attachments/files/19038489/androiddrive_it.zip)

**Comment by GustavLindberg99** [comment]
Could you please update the Italian translation for the new version? The attached file contains the new strings that need to be translated.

[androiddrive_it.zip](https://github.com/user-attachments/files/20273873/androiddrive_it.zip)

**Pull request merged**
